server:
  port: 8080
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/dreamix_animal_shelter

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true